version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: devops_test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops_user -d devops_test_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USERNAME: devops_user
      DB_PASSWORD: secure_password_123
      DB_NAME: devops_test_db
    depends_on:
      postgres-test:
        condition: service_healthy
    command: npm test